limit_req_status 429;

map $request_method $limit_key {
    POST    $binary_remote_addr;
    default "";
}

limit_req_zone $limit_key zone=upload:10m rate=2r/s;

server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    resolver 10.43.0.10;

    client_max_body_size 15m;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Content-Security-Policy "default-src 'self'; img-src 'self' https://cloud-virt-mai-waltzing-images.s3.eu-north-1.amazonaws.com; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;

    location /api/ {
        limit_req zone=upload burst=10 nodelay;

        proxy_pass http://backend-svc.imgr.svc.cluster.local:8080/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /image {
        set $upstream http://backend-svc.imgr.svc.cluster.local:8080;
        proxy_pass $upstream$request_uri;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /config.json {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}