apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yml
  - allow-dns.yml
  - allow-egress-external.yml
  - allow-frontend-ingress.yml
  - allow-backend-ingress.yml
  - allow-frontend-to-backend.yml
