apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imgr

resources:
  - namespace.yml
  - backend-deploy.yml
  - backend-service.yml
  - backend-pdb.yml
  - backend-hpa.yml
  - worker-deploy.yml
  - worker-pdb.yml
  - worker-hpa.yml
  - frontend-deploy.yml
  - frontend-service.yml
  - frontend-pdb.yml
  - netpol-default-deny.yml
  - netpol-allow-dns.yml
  - netpol-allow-egress-external.yml
  - netpol-allow-frontend-ingress.yml
  - netpol-allow-backend-ingress.yml
  - netpol-allow-frontend-to-backend.yml
